fn ml_domain() -> DomainSpec {
    let dataset = ml_type("dataset", Type::String);
    let model = ml_type("model", Type::String);
    let device = ml_type("device", Type::String);
    let resource_budget = ml_type("resource_budget", Type::Opaque);
    let training_config = ml_type("training_config", Type::Opaque);
    let training_run = ml_type("training_run", Type::Opaque);
    let inference_run = ml_type("inference_run", Type::Opaque);
    let evaluation_run = ml_type("evaluation_run", Type::Opaque);

    let types = [
        &dataset,
        &model,
        &device,
        &resource_budget,
        &training_config,
        &training_run,
        &inference_run,
        &evaluation_run,
    ]
    .iter()
    .filter_map(|ty| match ty {
        Type::Nominal(value) => Some(value.clone()),
        _ => None,
    })
    .collect();

    DomainSpec {
        name: "ml".to_string(),
        default_backend: None,
        artifacts: BTreeMap::new(),
        elements: BTreeMap::new(),
        properties: BTreeMap::new(),
        types,
        operations: vec![
            op(
                "open_dataset",
                &["open"],
                vec![lit("dataset"), slot("source", Type::String)],
                dataset.clone(),
                &["filesystem_read"],
            ),
            op(
                "transform_dataset",
                &["transform"],
                vec![slot("dataset", dataset.clone()), lit("using"), slot("transform", Type::String)],
                dataset.clone(),
                &[],
            ),
            op(
                "split_dataset",
                &["split"],
                vec![
                    slot("dataset", dataset.clone()),
                    lit("ratio"),
                    slot("ratio", Type::Number),
                    lit("seed"),
                    slot("seed", Type::Number),
                ],
                dataset.clone(),
                &[],
            ),
            op(
                "load_model",
                &["load"],
                vec![lit("model"), slot("identifier", Type::String)],
                model.clone(),
                &["model_load"],
            ),
            op(
                "build_cnn",
                &["build"],
                vec![
                    lit("cnn"),
                    lit("for"),
                    slot("classes", Type::Number),
                    lit("classes"),
                    lit("input"),
                    lit("channels"),
                    slot("input_channels", Type::Number),
                ],
                model.clone(),
                &[],
            ),
            op(
                "freeze_component",
                &["freeze"],
                vec![
                    slot("model", model.clone()),
                    lit("component"),
                    slot("component", Type::String),
                ],
                model.clone(),
                &[],
            ),
            op(
                "apply_lora",
                &["apply"],
                vec![
                    lit("lora"),
                    lit("to"),
                    slot("model", model.clone()),
                    lit("rank"),
                    slot("rank", Type::Number),
                    lit("alpha"),
                    slot("alpha", Type::Number),
                ],
                model.clone(),
                &[],
            ),
            op(
                "apply_qlora",
                &["adapt"],
                vec![
                    slot("model", model.clone()),
                    lit("with"),
                    lit("qlora"),
                    lit("rank"),
                    slot("rank", Type::Number),
                    lit("alpha"),
                    slot("alpha", Type::Number),
                    lit("quantization"),
                    slot("quantization_bits", Type::Number),
                    lit("bits"),
                    lit("targets"),
                    slot("targets", Type::String),
                ],
                model.clone(),
                &[],
            ),
            op(
                "select_device",
                &["select"],
                vec![lit("device"), slot("name", Type::String)],
                device.clone(),
                &[],
            ),
            op(
                "budget_resources",
                &["budget"],
                vec![
                    lit("resources"),
                    lit("memory"),
                    slot("memory_gb", Type::Number),
                    lit("gb"),
                    lit("workers"),
                    slot("workers", Type::Number),
                ],
                resource_budget.clone(),
                &[],
            ),
            op(
                "configure_training",
                &["configure"],
                vec![
                    lit("training"),
                    lit("for"),
                    slot("epochs", Type::Number),
                    lit("epochs"),
                    lit("using"),
                    lit("optimizer"),
                    slot("optimizer", Type::String),
                    lit("learning"),
                    lit("rate"),
                    slot("learning_rate", Type::Number),
                    lit("batch"),
                    lit("size"),
                    slot("batch_size", Type::Number),
                    lit("seed"),
                    slot("seed", Type::Number),
                ],
                training_config.clone(),
                &[],
            ),
            op(
                "plan_training",
                &["plan"],
                vec![
                    lit("training"),
                    lit("for"),
                    slot("epochs", Type::Number),
                    lit("epochs"),
                    lit("using"),
                    lit("optimizer"),
                    slot("optimizer", Type::String),
                    lit("learning"),
                    lit("rate"),
                    slot("learning_rate", Type::Number),
                    lit("batch"),
                    lit("size"),
                    slot("batch_size", Type::Number),
                    lit("seed"),
                    slot("seed", Type::Number),
                    lit("precision"),
                    slot("precision", Type::String),
                    lit("accumulate"),
                    slot("gradient_accumulation", Type::Number),
                    lit("steps"),
                    lit("checkpoint"),
                    lit("every"),
                    slot("checkpoint_every", Type::Number),
                    lit("steps"),
                ],
                training_config.clone(),
                &[],
            ),
            op(
                "train",
                &["train"],
                vec![
                    slot("model", model.clone()),
                    lit("using"),
                    slot("dataset", dataset.clone()),
                    lit("on"),
                    slot("device", device.clone()),
                    lit("for"),
                    slot("epochs", Type::Number),
                    lit("epochs"),
                ],
                training_run.clone(),
                &["compute", "model_training"],
            ),
            op(
                "fit",
                &["fit"],
                vec![
                    slot("model", model.clone()),
                    lit("using"),
                    slot("dataset", dataset.clone()),
                    lit("on"),
                    slot("device", device.clone()),
                    lit("with"),
                    slot("config", training_config.clone()),
                ],
                training_run.clone(),
                &["compute", "model_training"],
            ),
            op(
                "fit_budgeted",
                &["allocate"],
                vec![
                    slot("budget", resource_budget.clone()),
                    lit("to"),
                    lit("fit"),
                    slot("model", model.clone()),
                    lit("using"),
                    slot("dataset", dataset.clone()),
                    lit("on"),
                    slot("device", device.clone()),
                    lit("with"),
                    slot("config", training_config.clone()),
                ],
                training_run,
                &["compute", "model_training"],
            ),
            op(
                "infer",
                &["infer"],
                vec![
                    slot("model", model.clone()),
                    lit("on"),
                    slot("dataset", dataset.clone()),
                    lit("using"),
                    slot("device", device.clone()),
                ],
                inference_run,
                &["compute", "model_inference"],
            ),
            op(
                "evaluate",
                &["evaluate"],
                vec![
                    slot("model", model),
                    lit("on"),
                    slot("dataset", dataset),
                    lit("using"),
                    slot("device", device),
                    lit("metric"),
                    slot("metric", Type::String),
                ],
                evaluation_run,
                &["compute", "model_evaluation"],
            ),
        ],
    }
}

